import Head from "next/head";
import style from "@/styles/index.module.scss";
import Navbar from "@/components/Navbar";
import Pronounciation from "@/components/Pronounciation";
import Verb from "@/components/Verb";
import { ChangeEvent, useRef, useState } from "react";


export default function Home(props: { man: string; woman: string }) {
  let inputRef=useRef<HTMLInputElement>(null)
  const [inputWord,setInputWord] = useState<string|undefined>(" ")
  const data =[
    "(etc) a set of keys used to operate",
    "a component of many instruments including the piano",
    "a device with keys of a musical keyboard"
  ]
  // const inputHandler=(e:)=>{
  //   setInputWord(inputRef.current?.value)
  // }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${style.main}  ${style.light}`}>
        <div className={style.container}>
          <Navbar />
          <div className={style.search}>
            <input type="search" ref={inputRef}/>
            <button onClick={(e)=>{setInputWord(inputRef.current?.value);console.log(e)}}></button>
          </div>
          <Pronounciation input={inputWord}/>
          <Verb type={"verb"} meanings={data} synonym={"Piano keyboard"} />
        </div>
      </main>
    </>
  );
}

// export async function getStaticProps(){

//   const app_id = "13d104e6";
//   const app_key = "7d6501aac00aec8253fded44494717b4";
//   const wordId = "ace";
//   const fields = "pronunciations";
//   const strictMatch = "false";
//   const options = {
//     host: "od-api.oxforddictionaries.com",
//     port: "443",
//     path:
//       "/api/v2/entries/en-gb/" +
//       wordId +
//       "?fields=" +
//       fields +
//       "&strictMatch=" +
//       strictMatch,
//     method: "GET",
//     headers: {
//       app_id: app_id,
//       app_key: app_key,
//     },
//   };
//   let res = await https.get(options, (resp:Http2ServerResponse) => {
//     let body = "";
//     resp.on("data", (d) => {
//       body += d;
//     });
//     resp.on("end", () => {
//       let parsed = JSON.stringify(body);
//       return parsed
//     });
//   });
//   console.log(res)
//   return {
//     props:{
//       res:"kill"
//     }
//   }

// }

// const https = require("https");
// const app_id = "<my app_id>";
// const app_key = "<my app_key>";
// const wordId = "ace";
// const fields = "pronunciations";
// const strictMatch = "false";
// const options = {
//   host: "od-api.oxforddictionaries.com",
//   port: "443",
//   path:
//     "/api/v2/entries/en-gb/" +
//     wordId +
//     "?fields=" +
//     fields +
//     "&strictMatch=" +
//     strictMatch,
//   method: "GET",
//   headers: {
//     app_id: app_id,
//     app_key: app_key,
//   },
// };
// https.get(options, (resp) => {
//   let body = "";
//   resp.on("data", (d) => {
//     body += d;
//   });
//   resp.on("end", () => {
//     let parsed = JSON.stringify(body);
//     console.log(parsed);
//   });
// });
